### ISSUE TITLE
autojump image not loaded!

### ISSUE THREAD

**Issue by Zeroxus** [songrotek/wechat_jump_end_to_end#1]
```
PS E:\Code\wechat_jump_end_to_end> python .\run_android.py
load model
load ok
Traceback (most recent call last):
  File ".\run_android.py", line 133, in <module>
    main()
  File ".\run_android.py", line 116, in main
    image = Image.open('./autojump.png')
  File "C:\Users\Avalon\Anaconda3\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'
```

**Comment by Zeroxus** [comment]
参照[IOError: cannot identify image file './1.png'](https://github.com/wangshub/wechat_jump_game/issues/194)解决
