### ISSUE TITLE
如下文字显示，这是为啥？

### ISSUE THREAD

**Issue by ylrh3** [songrotek/wechat_jump_end_to_end#6]
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/wechat_jump_end_to_end-master (1)/wechat_jump_end_to_end-master/run_android.py", line 133, in <module>
    main()
  File "C:/Users/Administrator/Desktop/wechat_jump_end_to_end-master (1)/wechat_jump_end_to_end-master/run_android.py", line 116, in main
    image = Image.open('./autojump.png')
  File "C:\Program Files\Anaconda3\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

Process finished with exit code 1

**Comment by cbhlzds** [comment]
我花了好几个小时排查，终于搞定了。这里代码改成如下：
def pull_screenshot(name="autojump.png"):
    process = subprocess.Popen('adb exec-out screencap -p', shell=True, stdout=subprocess.PIPE)
    screenshot = process.stdout.read()
    f = open(name, 'wb')
    f.write(screenshot)
    f.close()

**Comment by CalmArrow** [comment]
还有一种更简单的办法：
os.system('adb shell screencap -p /sdcard/autojump.png')
os.system('adb pull /sdcard/autojump.png .')
